# Generated by Django 4.1.5 on 2023-06-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkr', '0008_alter_kompetenzkarte_alle_teil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fach',
            options={'ordering': ['fach'], 'verbose_name_plural': 'Fächer'},
        ),
        migrations.AddField(
            model_name='kompetenzkarte',
            name='medienkenntnisse_lul',
            field=models.CharField(default='-', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kompetenzkarte',
            name='vorwissen_sus',
            field=models.CharField(default='-', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='alle_teil',
            field=models.CharField(blank=True, choices=[('0', 'für alle '), ('1', 'eine Teilgruppe')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='info',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='medienkompetenz',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='kompetenzkarte',
            name='technik',
            field=models.CharField(max_length=400),
        ),
    ]
