# Generated by Django 4.1.5 on 2023-06-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mkr', '0009_alter_fach_options_alter_kompetenzkarte_alle_teil_and_more'),
        ('mkr', '0009_alter_fach_options_and_more'),
    ]

    operations = [
    ]
