# Generated by Django 4.0.5 on 2022-07-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_allowedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedemail',
            name='school',
            field=models.CharField(default='genm', max_length=100),
            preserve_default=False,
        ),
    ]
