# Generated by Django 4.0.5 on 2022-12-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_allowed_emails_allowedemail_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('noreply-mail', 'noreply-E-Mail-Absenderadresse zum Versand der Codes'), ('mail_text', 'Mailtext zum Versand der Codes')], max_length=50)),
                ('setting', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
