# Generated by Django 4.1.4 on 2022-12-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(choices=[('noreply-mail', 'noreply-E-Mail-Absenderadresse zum Versand der Codes')], max_length=50),
        ),
    ]
