# Generated by Django 4.1.4 on 2022-12-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_config_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(choices=[('noreply-mail', 'noreply-E-Mail-Absenderadresse'), ('mail_text', 'Mailtext zum Versand der Registrierungslinks')], max_length=50),
        ),
    ]
